[package]
name = "formats"
version = "0.1.0"
edition = "2024"

[lib]
path = "src/lib.rs"

[dependencies]
foundation = { path = "../foundation" }
scene = { path = "../scene" }
blake3 = "1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
