[package]
name = "layers"
version = "0.1.0"
edition = "2024"

[lib]
path = "src/lib.rs"

[dependencies]
foundation = { path = "../foundation" }
scene = { path = "../scene" }
gpu = { path = "../gpu" }
streaming = { path = "../streaming" }
