[book]
# Standard mdBook layout.
src = "."
title = "Atlas"

[build]
build-dir = "book"

[output.html]
# This repo is deployed as a *project* site: https://<user>.github.io/atlas/
site-url = "/atlas/docs/"
